services:
  db:
    image: mysql:8.0.3
    ports:
      - "3307:3306"
    volumes:
      - ./.data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp3
    ports:
      - "3002:3000"
    depends_on:
      - db

